#define COLOR_WHITE		  0xFFFFFFFF

#define COLOR_USAGE		  0xCDFF00FF // kuning pucat
#define COLOR_ERROR       0xFF0A0EEE // merah
#define COLOR_SUCCESS     0x00FF00FF // Hijau
#define COLOR_INFO        0x00D1FFFF  // biru muda
#define COLOR_SERVER      0xA0A0A0FF // abu abu

#define COLOR_FADE1 0xB9B5B9FF
#define COLOR_FADE2 0x8E9093FF
#define COLOR_FADE3 0x6A6F6EFF
#define COLOR_FADE4 0x24292CFF

#define MYSQL_HOST "localhost"
#define MYSQL_USER "root"
#define MYSQL_PASS ""
#define MYSQL_DBNAME "tansa"

#define DEFAULT_POS_X 1958.2170 
#define DEFAULT_POS_Y 1343.0073
#define DEFAULT_POS_Z 15.3746
#define DEFAULT_POS_A 268.6832

#define GAMEMODE "Omp WP-RP"

#define NAMETAG_DISTANCE 25.0
#define CHAT_RADIUS 25.0